port: {{ .Env.PORT }}
managementApiSecret: {{ .Env.MANAGEMENT_API_SECRET }}
databases:
  default:
    migrations: true
    connector: {{ .Env.DATABASE_CONNECTOR }}
    host: {{ .Env.DATABASE_HOST }}
    port: {{ .Env.DATABASE_PORT }}
    user: {{ .Env.DATABASE_USER }}
    password: {{ .Env.DATABASE_PASSWORD }}
